"""
PDF Generation Service — Training Plan Export

Renders a training plan to PDF using WeasyPrint + Jinja2.

Spec:
- Page 1: summary (athlete, plan info, pace reference card)
- Pages 2+: weekly workout tables, one week per section
- Footer every page: "Generated by StrideIQ — strideiq.run | Page X of Y"
- No external asset fetches — all CSS is inline
- Unit display: weekly tables use athlete preferred unit only;
  pace reference card shows both min/mi and min/km
"""

import concurrent.futures
import io
import re
import logging
from datetime import datetime, date
from typing import Optional

logger = logging.getLogger(__name__)

# ─── Generation guardrails ─────────────────────────────────────────────────────
# These protect the API process from runaway memory and wall-clock time.
# Values are deliberately generous — normal plans (8-24 weeks) are well inside.

#: Maximum number of distinct week numbers accepted from the DB.
#: 60 weeks covers the longest credible ultra-training block.
MAX_PLAN_WEEKS: int = 60

#: Maximum number of raw PlannedWorkout rows accepted before grouping.
#: 60 weeks × 7 days = 420; cap at 500 gives headroom for edge cases.
MAX_WORKOUT_ROWS: int = 500

#: Maximum output size in bytes.  Typical plans render 100-500 KB;
#: 20 MB indicates something went wrong with the render.
MAX_PDF_BYTES: int = 20 * 1024 * 1024  # 20 MB

#: Wall-clock timeout for the WeasyPrint render call.
#: Normal renders complete in <5s; 30s timeout catches pathological input.
GENERATION_TIMEOUT_SECONDS: int = 30


# ─── Pace helpers ─────────────────────────────────────────────────────────────

def _fmt_mmss(total_seconds: Optional[float]) -> Optional[str]:
    """Format a seconds value as M:SS."""
    if total_seconds is None or total_seconds <= 0:
        return None
    s = int(total_seconds)
    return f"{s // 60}:{s % 60:02d}"


def _sec_km_to_sec_mi(sec_per_km: Optional[float]) -> Optional[float]:
    """Convert pace in sec/km to sec/mi."""
    if sec_per_km is None:
        return None
    return sec_per_km * 1.60934


def _fmt_pace(sec_per_unit: Optional[float]) -> str:
    """Format pace seconds as M:SS, or — if None."""
    result = _fmt_mmss(sec_per_unit)
    return result if result else "—"


# ─── Distance helpers ─────────────────────────────────────────────────────────

def _fmt_distance(km: Optional[float], preferred_units: str) -> str:
    if km is None or km == 0:
        return "—"
    if preferred_units == "imperial":
        return f"{km * 0.621371:.1f} mi"
    return f"{km:.1f} km"


# ─── Filename sanitizer ───────────────────────────────────────────────────────

def sanitize_pdf_filename(name: str) -> str:
    """Remove unsafe characters from a content-disposition filename."""
    # Strip anything not alphanumeric, space, hyphen, or underscore
    safe = re.sub(r'[^\w\s\-]', '', name or "")
    # Collapse whitespace to underscores
    safe = re.sub(r'\s+', '_', safe.strip())
    return safe[:50] or "training_plan"


# ─── Pace reference card ──────────────────────────────────────────────────────

def _build_pace_card(baseline_rpi: Optional[float]) -> list:
    """
    Build 5-zone pace reference card from plan baseline RPI.
    Returns list of dicts: [{zone, mi, km}, ...].
    Uses calculate_training_paces() which implements Daniels/Gilbert physics.
    Falls back to empty list if RPI missing or calculation fails.
    """
    if not baseline_rpi or baseline_rpi <= 0:
        return []
    try:
        from services.rpi_calculator import calculate_training_paces
        raw = calculate_training_paces(float(baseline_rpi))
    except Exception as exc:
        logger.warning("pace_card: calculate_training_paces failed: %s", exc)
        return []

    zones = [
        ("Easy",        "easy"),
        ("Marathon",    "marathon"),
        ("Threshold",   "threshold"),
        ("Interval",    "interval"),
        ("Repetition",  "repetition"),
    ]

    card = []
    for label, key in zones:
        zone_data = raw.get(key, {})
        if isinstance(zone_data, dict):
            mi = zone_data.get("mi") or "—"
            km = zone_data.get("km") or "—"
            # Append unit labels
            mi_disp = f"{mi}/mi" if mi != "—" else "—"
            km_disp = f"{km}/km" if km != "—" else "—"
        else:
            mi_disp = km_disp = "—"
        card.append({"zone": label, "mi": mi_disp, "km": km_disp})

    return card


# ─── Workout row builder ──────────────────────────────────────────────────────

_DAY_NAMES = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


def _build_workout_row(w, preferred_units: str) -> dict:
    """Convert a PlannedWorkout model instance to a table row dict."""
    if w is None or w.workout_type == "rest":
        return None  # caller handles as rest row

    # Format pace: prefer structured pace fields; fall back to coach_notes
    pace_str = "—"
    if w.target_pace_per_km_seconds and w.target_pace_per_km_seconds > 0:
        if preferred_units == "imperial":
            lo = _fmt_pace(_sec_km_to_sec_mi(w.target_pace_per_km_seconds))
            hi_sec = _sec_km_to_sec_mi(w.target_pace_per_km_seconds_max) if w.target_pace_per_km_seconds_max else None
            if hi_sec:
                pace_str = f"{lo}–{_fmt_pace(hi_sec)}/mi"
            else:
                pace_str = f"{lo}/mi"
        else:
            lo = _fmt_pace(w.target_pace_per_km_seconds)
            if w.target_pace_per_km_seconds_max:
                pace_str = f"{lo}–{_fmt_pace(w.target_pace_per_km_seconds_max)}/km"
            else:
                pace_str = f"{lo}/km"
    elif w.coach_notes:
        pace_str = w.coach_notes[:80]

    return {
        "type": w.workout_type.replace("_", " ").title(),
        "title": w.title or "",
        "distance": _fmt_distance(w.target_distance_km, preferred_units),
        "pace": pace_str,
        "notes": (w.description or "")[:150],
        "is_rest": False,
    }


# ─── Main generator ───────────────────────────────────────────────────────────

def generate_plan_pdf(plan, workouts, athlete) -> bytes:
    """
    Generate a PDF for a training plan and return raw bytes.

    Args:
        plan: TrainingPlan model instance (must be owned by athlete)
        workouts: list of PlannedWorkout instances ordered by week/day
        athlete: Athlete model instance (for preferred_units, display_name)

    Returns:
        Raw PDF bytes (starts with b'%PDF')

    Raises:
        RuntimeError: if WeasyPrint is not installed or generation fails
    """
    try:
        import weasyprint
    except ImportError:
        raise RuntimeError(
            "WeasyPrint is not installed. Add 'weasyprint' to requirements.txt "
            "and rebuild the API image."
        )

    from jinja2 import Environment, BaseLoader

    preferred_units = (getattr(athlete, "preferred_units", None) or "imperial").lower()
    athlete_name = (
        getattr(athlete, "display_name", None)
        or getattr(athlete, "email", None)
        or ""
    )

    # ── Guardrail 1: input scope cap ───────────────────────────────────────────
    # Fail fast before any template work.  Both checks raise RuntimeError so
    # the endpoint can return 503 without leaking internal detail.
    n_workouts = len(workouts)
    if n_workouts > MAX_WORKOUT_ROWS:
        raise RuntimeError(
            f"Plan has {n_workouts} workout rows, which exceeds the "
            f"render limit of {MAX_WORKOUT_ROWS}. "
            "Split the plan or contact support."
        )

    # ── Group workouts by week ─────────────────────────────────────────────────
    weeks_map: dict[int, list] = {}
    for w in workouts:
        wn = w.week_number
        if wn not in weeks_map:
            weeks_map[wn] = []
        weeks_map[wn].append(w)

    n_weeks = len(weeks_map)
    if n_weeks > MAX_PLAN_WEEKS:
        raise RuntimeError(
            f"Plan spans {n_weeks} weeks, which exceeds the "
            f"render limit of {MAX_PLAN_WEEKS}. "
            "Split the plan or contact support."
        )

    # ── Build week sections ────────────────────────────────────────────────────
    week_sections = []
    for week_num in sorted(weeks_map.keys()):
        week_workouts = sorted(weeks_map[week_num], key=lambda w: w.day_of_week)
        phase = (week_workouts[0].phase if week_workouts else "").capitalize()
        total_km = sum(w.target_distance_km or 0 for w in week_workouts if w.workout_type != "rest")

        rows = []
        for day_idx in range(7):
            day_name = _DAY_NAMES[day_idx]
            w = next((x for x in week_workouts if x.day_of_week == day_idx), None)

            if w is None or w.workout_type == "rest":
                rows.append({
                    "day": day_name,
                    "type": "Rest",
                    "title": "Rest",
                    "distance": "—",
                    "pace": "—",
                    "notes": "",
                    "is_rest": True,
                })
            else:
                row = _build_workout_row(w, preferred_units)
                row["day"] = day_name
                rows.append(row)

        week_sections.append({
            "week_number": week_num,
            "phase": phase,
            "total_distance": _fmt_distance(total_km, preferred_units),
            "rows": rows,
        })

    # ── Build pace reference card ──────────────────────────────────────────────
    pace_card = _build_pace_card(getattr(plan, "baseline_rpi", None))

    # ── Format plan metadata ───────────────────────────────────────────────────
    def _fmt_date(d) -> str:
        if d is None:
            return "—"
        if isinstance(d, (date, datetime)):
            return d.strftime("%B %d, %Y")
        return str(d)

    def _fmt_distance_m(meters: Optional[int]) -> str:
        if not meters:
            return "—"
        dist_map = {
            5000: "5K", 10000: "10K",
            21097: "Half Marathon", 42195: "Marathon",
        }
        return dist_map.get(meters, f"{meters / 1000:.1f} km")

    ctx = {
        "plan_name": plan.name or "Training Plan",
        "athlete_name": athlete_name,
        "goal_race_name": plan.goal_race_name or "",
        "goal_race_date": _fmt_date(plan.goal_race_date),
        "goal_race_distance": _fmt_distance_m(getattr(plan, "goal_race_distance_m", None)),
        "total_weeks": plan.total_weeks,
        "start_date": _fmt_date(getattr(plan, "plan_start_date", None)),
        "end_date": _fmt_date(getattr(plan, "plan_end_date", None)),
        "baseline_rpi": plan.baseline_rpi,
        "generated_at": datetime.now().strftime("%B %d, %Y"),
        "preferred_units": preferred_units,
        "pace_card": pace_card,
        "weeks": week_sections,
    }

    # ── Render HTML ────────────────────────────────────────────────────────────
    env = Environment(loader=BaseLoader())
    template_src = _load_template()
    template = env.from_string(template_src)
    html_content = template.render(**ctx)

    # ── Guardrail 2: timeout-protected render ──────────────────────────────────
    def _do_render() -> bytes:
        inner_buf = io.BytesIO()
        weasyprint.HTML(string=html_content, base_url=None).write_pdf(inner_buf)
        return inner_buf.getvalue()

    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
        future = executor.submit(_do_render)
        try:
            pdf_bytes = future.result(timeout=GENERATION_TIMEOUT_SECONDS)
        except concurrent.futures.TimeoutError:
            raise RuntimeError(
                f"PDF generation timed out after {GENERATION_TIMEOUT_SECONDS}s. "
                "Try again or contact support if the issue persists."
            )

    if not pdf_bytes or not pdf_bytes.startswith(b"%PDF"):
        raise RuntimeError("WeasyPrint produced invalid or empty PDF output")

    # ── Guardrail 3: output byte-size cap ──────────────────────────────────────
    if len(pdf_bytes) > MAX_PDF_BYTES:
        raise RuntimeError(
            f"Generated PDF is {len(pdf_bytes):,} bytes, which exceeds the "
            f"{MAX_PDF_BYTES // (1024 * 1024)} MB safety limit. "
            "Contact support."
        )

    logger.info(
        "plan_pdf: generated %d bytes for plan=%s weeks=%d",
        len(pdf_bytes), getattr(plan, "id", "?"), len(week_sections),
    )
    return pdf_bytes


# ─── HTML template (inline to avoid filesystem dependency) ────────────────────

def _load_template() -> str:
    """Return the Jinja2 HTML template string."""
    return r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{{ plan_name }}</title>
<style>
  /* ── Page layout ── */
  @page {
    size: Letter;
    margin: 18mm 18mm 22mm 18mm;
    @bottom-center {
      content: "Generated by StrideIQ \2014 strideiq.run  |  Page " counter(page) " of " counter(pages);
      font-family: sans-serif;
      font-size: 8pt;
      color: #888;
    }
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: "DejaVu Sans", Arial, Helvetica, sans-serif;
    font-size: 9.5pt;
    color: #1a1a1a;
    background: #fff;
    line-height: 1.45;
  }

  /* ── Summary page ── */
  .brand {
    font-size: 11pt;
    font-weight: bold;
    color: #c2410c;
    letter-spacing: 0.04em;
    margin-bottom: 4px;
  }
  h1.plan-title {
    font-size: 20pt;
    font-weight: bold;
    color: #111;
    margin-bottom: 8px;
    line-height: 1.15;
  }
  .meta-row {
    display: flex;
    flex-wrap: wrap;
    gap: 6px 18px;
    margin-bottom: 18px;
    color: #444;
    font-size: 9pt;
  }
  .meta-item strong { color: #111; }

  /* ── Pace reference card ── */
  .section-label {
    font-size: 8pt;
    font-weight: bold;
    color: #c2410c;
    letter-spacing: 0.09em;
    text-transform: uppercase;
    margin-bottom: 5px;
    margin-top: 16px;
  }
  table.pace-card {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 22px;
  }
  table.pace-card th {
    background: #f5f5f5;
    font-size: 8.5pt;
    font-weight: bold;
    color: #333;
    padding: 5px 8px;
    text-align: left;
    border: 1px solid #ddd;
  }
  table.pace-card td {
    padding: 5px 8px;
    border: 1px solid #e0e0e0;
    font-size: 9pt;
    color: #1a1a1a;
  }
  table.pace-card tr:nth-child(even) td { background: #fafafa; }

  /* ── Page break before each week section ── */
  .week-section { page-break-before: always; }
  .week-section:first-child { page-break-before: avoid; }

  .week-header {
    display: flex;
    align-items: baseline;
    gap: 12px;
    margin-bottom: 6px;
    padding-bottom: 4px;
    border-bottom: 2px solid #c2410c;
  }
  .week-num {
    font-size: 13pt;
    font-weight: bold;
    color: #111;
  }
  .week-phase {
    font-size: 9pt;
    font-weight: bold;
    color: #c2410c;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }
  .week-volume {
    font-size: 8.5pt;
    color: #666;
    margin-left: auto;
  }

  /* ── Workout table ── */
  table.workouts {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 8px;
    page-break-inside: avoid;
  }
  table.workouts th {
    background: #f0f0f0;
    font-size: 8pt;
    font-weight: bold;
    color: #333;
    padding: 4px 7px;
    text-align: left;
    border: 1px solid #ccc;
  }
  table.workouts td {
    padding: 5px 7px;
    border: 1px solid #e0e0e0;
    font-size: 8.5pt;
    vertical-align: top;
    color: #1a1a1a;
  }
  table.workouts tr.rest-row td {
    color: #aaa;
    font-style: italic;
    background: #fafafa;
  }
  table.workouts tr:nth-child(even):not(.rest-row) td {
    background: #fcfcfc;
  }
  .type-badge {
    display: inline-block;
    font-size: 7.5pt;
    font-weight: bold;
    padding: 1px 4px;
    border-radius: 3px;
    white-space: nowrap;
    background: #f0ebe8;
    color: #7c2d12;
  }
  .col-day   { width: 7%;  }
  .col-type  { width: 14%; }
  .col-title { width: 22%; }
  .col-dist  { width: 10%; text-align: right; }
  .col-pace  { width: 14%; }
  .col-notes { width: 33%; }
</style>
</head>
<body>

<!-- ════════════════════ PAGE 1 — PLAN SUMMARY ════════════════════ -->
<div class="brand">StrideIQ</div>
<h1 class="plan-title">{{ plan_name }}</h1>

<div class="meta-row">
  {% if athlete_name %}<span class="meta-item"><strong>Athlete:</strong> {{ athlete_name }}</span>{% endif %}
  {% if goal_race_name %}<span class="meta-item"><strong>Race:</strong> {{ goal_race_name }}</span>{% endif %}
  {% if goal_race_date %}<span class="meta-item"><strong>Race date:</strong> {{ goal_race_date }}</span>{% endif %}
  {% if goal_race_distance %}<span class="meta-item"><strong>Distance:</strong> {{ goal_race_distance }}</span>{% endif %}
  <span class="meta-item"><strong>Plan length:</strong> {{ total_weeks }} weeks</span>
  {% if start_date %}<span class="meta-item"><strong>Start:</strong> {{ start_date }}</span>{% endif %}
  {% if end_date %}<span class="meta-item"><strong>End:</strong> {{ end_date }}</span>{% endif %}
  {% if baseline_rpi %}<span class="meta-item"><strong>Fitness Index (RPI):</strong> {{ "%.1f"|format(baseline_rpi) }}</span>{% endif %}
  <span class="meta-item"><strong>Generated:</strong> {{ generated_at }}</span>
</div>

<!-- Pace reference card -->
{% if pace_card %}
<div class="section-label">Training Pace Reference</div>
<table class="pace-card">
  <thead>
    <tr>
      <th>Zone</th>
      <th>Per Mile (min/mi)</th>
      <th>Per Kilometre (min/km)</th>
    </tr>
  </thead>
  <tbody>
    {% for row in pace_card %}
    <tr>
      <td><strong>{{ row.zone }}</strong></td>
      <td>{{ row.mi }}</td>
      <td>{{ row.km }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

<!-- ════════════════════ PAGES 2+ — WEEKLY TABLES ════════════════════ -->
{% for week in weeks %}
<div class="week-section">
  <div class="week-header">
    <span class="week-num">Week {{ week.week_number }}</span>
    <span class="week-phase">{{ week.phase }}</span>
    <span class="week-volume">{{ week.total_distance }}</span>
  </div>

  <table class="workouts">
    <thead>
      <tr>
        <th class="col-day">Day</th>
        <th class="col-type">Type</th>
        <th class="col-title">Workout</th>
        <th class="col-dist">Distance</th>
        <th class="col-pace">Pace Target</th>
        <th class="col-notes">Notes</th>
      </tr>
    </thead>
    <tbody>
      {% for row in week.rows %}
      <tr {% if row.is_rest %}class="rest-row"{% endif %}>
        <td>{{ row.day }}</td>
        <td>{% if not row.is_rest %}<span class="type-badge">{{ row.type }}</span>{% else %}—{% endif %}</td>
        <td>{{ row.title }}</td>
        <td>{{ row.distance }}</td>
        <td>{{ row.pace }}</td>
        <td>{% if not row.is_rest %}{{ row.notes }}{% endif %}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endfor %}

</body>
</html>"""
