"""
Segments Builder — populates unified segment schema on workouts.

Every structured workout MUST have segments populated.
Easy and rest days may have null segments.

Segment types: warmup, cooldown, work, float, jog_rest, easy,
threshold, interval, stride, steady, hike, fatigue_resistance, uphill_tm.

Every segment includes BOTH pace_pct_mp (internal) AND pace_sec_per_km
(the concrete number).  The effort description is generated by
effort_mapper.describe_segment().

Ref: Algorithm Spec §5 ("Segments Schema").
"""

from __future__ import annotations

from typing import List, Optional

from .effort_mapper import describe_segment
from .models import PaceLadder, WorkoutSegment


def _resolve_pace(ladder: PaceLadder, pct: int, zone: str | None = None) -> float:
    """Resolve pace: use named Daniels zone if specified, otherwise arithmetic.

    This is the one place that decides whether a segment gets the Daniels
    value or the arithmetic ladder value.  When a workout is conceptually
    at "easy" effort, pass zone="easy" and the Daniels easy pace wins.
    When it's at an arbitrary percentage (e.g. 90%), pass zone=None.
    """
    _ZONE_MAP = {
        "easy": ladder.easy,
        "long": ladder.long,
        "marathon": ladder.marathon,
        "threshold": ladder.threshold,
        "interval": ladder.interval,
        "repetition": ladder.repetition,
        "recovery": ladder.recovery,
    }
    if zone and zone in _ZONE_MAP:
        return _ZONE_MAP[zone]
    return ladder.pace_for_pct(pct)


def warmup(
    ladder: PaceLadder,
    distance_km: float = 2.0,
    pct: int = 80,
    *,
    is_beginner: bool = False,
) -> WorkoutSegment:
    pace = _resolve_pace(ladder, pct, zone="easy")
    return WorkoutSegment(
        type="warmup",
        pace_pct_mp=pct,
        pace_sec_per_km=pace,
        distance_km=distance_km,
        description=describe_segment(pct, pace, is_beginner=is_beginner),
    )


def cooldown(
    ladder: PaceLadder,
    distance_km: float = 2.0,
    pct: int = 80,
    *,
    is_beginner: bool = False,
) -> WorkoutSegment:
    pace = _resolve_pace(ladder, pct, zone="easy")
    return WorkoutSegment(
        type="cooldown",
        pace_pct_mp=pct,
        pace_sec_per_km=pace,
        distance_km=distance_km,
        description=describe_segment(pct, pace, is_beginner=is_beginner),
    )


def work_segment(
    ladder: PaceLadder,
    pct: int,
    *,
    zone: str | None = None,
    distance_km: Optional[float] = None,
    duration_min: Optional[float] = None,
    reps: Optional[int] = None,
    rest_min: Optional[float] = None,
    is_beginner: bool = False,
) -> WorkoutSegment:
    pace = _resolve_pace(ladder, pct, zone=zone)
    return WorkoutSegment(
        type="work",
        pace_pct_mp=pct,
        pace_sec_per_km=pace,
        distance_km=distance_km,
        duration_min=duration_min,
        reps=reps,
        rest_min=rest_min,
        description=describe_segment(pct, pace, is_beginner=is_beginner),
    )


def float_segment(
    ladder: PaceLadder,
    pct: int = 85,
    *,
    distance_km: Optional[float] = None,
    duration_min: Optional[float] = None,
    is_beginner: bool = False,
) -> WorkoutSegment:
    pace = ladder.pace_for_pct(pct)
    return WorkoutSegment(
        type="float",
        pace_pct_mp=pct,
        pace_sec_per_km=pace,
        distance_km=distance_km,
        duration_min=duration_min,
        description=describe_segment(pct, pace, is_beginner=is_beginner),
    )


def jog_rest(
    ladder: PaceLadder,
    duration_min: float,
    pct: int = 75,
    *,
    is_beginner: bool = False,
) -> WorkoutSegment:
    pace = _resolve_pace(ladder, pct, zone="recovery")
    return WorkoutSegment(
        type="jog_rest",
        pace_pct_mp=pct,
        pace_sec_per_km=pace,
        duration_min=duration_min,
        description=describe_segment(pct, pace, is_beginner=is_beginner),
    )


def stride_segment(
    ladder: PaceLadder,
    reps: int = 6,
    duration_sec: float = 20.0,
    pct: int = 120,
    *,
    is_beginner: bool = False,
) -> WorkoutSegment:
    pace = ladder.pace_for_pct(pct)
    return WorkoutSegment(
        type="stride",
        pace_pct_mp=pct,
        pace_sec_per_km=pace,
        duration_min=duration_sec / 60.0,
        reps=reps,
        description=describe_segment(pct, pace, is_beginner=is_beginner),
    )


def steady_segment(
    ladder: PaceLadder,
    pct: int = 90,
    *,
    distance_km: Optional[float] = None,
    duration_min: Optional[float] = None,
    is_beginner: bool = False,
) -> WorkoutSegment:
    """Post-workout race-effort running (e.g. '2mi steady at 50K effort')."""
    pace = ladder.pace_for_pct(pct)
    return WorkoutSegment(
        type="steady",
        pace_pct_mp=pct,
        pace_sec_per_km=pace,
        distance_km=distance_km,
        duration_min=duration_min,
        description=describe_segment(pct, pace, is_beginner=is_beginner),
    )


def uphill_tm_segment(
    ladder: PaceLadder,
    pct: int = 80,
    *,
    duration_min: Optional[float] = None,
    grade_pct: float = 12.0,
    is_beginner: bool = False,
) -> WorkoutSegment:
    pace = ladder.pace_for_pct(pct)
    return WorkoutSegment(
        type="uphill_tm",
        pace_pct_mp=pct,
        pace_sec_per_km=pace,
        duration_min=duration_min,
        grade_pct=grade_pct,
        description=describe_segment(pct, pace, is_beginner=is_beginner),
    )


def fatigue_resistance_segment(
    ladder: PaceLadder,
    pct: int = 110,
    *,
    reps: int = 5,
    duration_sec: float = 40.0,
    is_beginner: bool = False,
) -> WorkoutSegment:
    """Short hard hills at END of long run, under glycogen depletion."""
    pace = ladder.pace_for_pct(pct)
    return WorkoutSegment(
        type="fatigue_resistance",
        pace_pct_mp=pct,
        pace_sec_per_km=pace,
        duration_min=duration_sec / 60.0,
        reps=reps,
        description=describe_segment(pct, pace, is_beginner=is_beginner),
    )


def hike_segment(
    ladder: PaceLadder,
    pct: int = 70,
    *,
    duration_min: Optional[float] = None,
    distance_km: Optional[float] = None,
    is_beginner: bool = False,
) -> WorkoutSegment:
    """Walking/hiking interval for beginners and ultra athletes."""
    pace = ladder.pace_for_pct(pct) * 1.3  # hike pace is ~30% slower than easy run
    return WorkoutSegment(
        type="hike",
        pace_pct_mp=pct,
        pace_sec_per_km=pace,
        duration_min=duration_min,
        distance_km=distance_km,
        description=describe_segment(pct, pace, is_beginner=is_beginner),
    )


def build_segments(
    workout_type: str,
    ladder: PaceLadder,
    params: dict,
) -> List[WorkoutSegment]:
    """Build a segment list for a given workout type.

    This is the general-purpose entry point.  Phase 2 will add workout-
    specific builders in workout_library.py that call the segment
    primitives above directly.  For now, this supports basic structures.

    Args:
        workout_type: Registered workout type key.
        ladder: The athlete's pace ladder.
        params: Workout-specific parameters (reps, distance, pct, etc).

    Returns:
        List of WorkoutSegment objects.
    """
    is_beginner = params.get("is_beginner", False)

    if workout_type == "easy":
        pct = params.get("pct", 80)
        pace = _resolve_pace(ladder, pct, zone="easy")
        return [
            WorkoutSegment(
                type="easy",
                pace_pct_mp=pct,
                pace_sec_per_km=pace,
                distance_km=params.get("distance_km"),
                description=describe_segment(pct, pace, is_beginner=is_beginner),
            )
        ]

    if workout_type == "easy_strides":
        pct = params.get("pct", 80)
        pace = _resolve_pace(ladder, pct, zone="easy")
        return [
            WorkoutSegment(
                type="easy",
                pace_pct_mp=pct,
                pace_sec_per_km=pace,
                distance_km=params.get("distance_km"),
                description=describe_segment(pct, pace, is_beginner=is_beginner),
            ),
            stride_segment(ladder, reps=params.get("stride_reps", 6), is_beginner=is_beginner),
        ]

    if workout_type == "threshold_cruise":
        return _build_threshold_cruise(ladder, params, is_beginner)

    if workout_type == "vo2max_track":
        return _build_vo2max_track(ladder, params, is_beginner)

    return []


def _build_threshold_cruise(
    ladder: PaceLadder,
    params: dict,
    is_beginner: bool,
) -> List[WorkoutSegment]:
    """Flat tempo/cruise intervals at threshold effort."""
    reps = params.get("reps", 3)
    rep_duration = params.get("rep_duration_min", 10.0)
    rest = params.get("rest_min", 2.0)
    pct = params.get("pct", 105)

    segments: List[WorkoutSegment] = [warmup(ladder, is_beginner=is_beginner)]
    for i in range(reps):
        segments.append(work_segment(
            ladder, pct, zone="threshold",
            duration_min=rep_duration, is_beginner=is_beginner,
        ))
        if i < reps - 1:
            segments.append(jog_rest(ladder, rest, is_beginner=is_beginner))
    segments.append(cooldown(ladder, is_beginner=is_beginner))
    return segments


def _build_vo2max_track(
    ladder: PaceLadder,
    params: dict,
    is_beginner: bool,
) -> List[WorkoutSegment]:
    """Track intervals at 5K-effort."""
    reps = params.get("reps", 5)
    rep_distance = params.get("rep_distance_km", 1.0)
    rest = params.get("rest_min", 3.0)
    pct = params.get("pct", 115)

    segments: List[WorkoutSegment] = [warmup(ladder, is_beginner=is_beginner)]
    for i in range(reps):
        segments.append(work_segment(
            ladder, pct, zone="interval",
            distance_km=rep_distance, is_beginner=is_beginner,
        ))
        if i < reps - 1:
            segments.append(jog_rest(ladder, rest, is_beginner=is_beginner))
    segments.append(cooldown(ladder, is_beginner=is_beginner))
    return segments
