"""add_knowledge_base_tables

Revision ID: 28b8df012709
Revises: cfcf3fd63cf0
Create Date: 2026-01-04 20:55:35.121090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b8df012709'
down_revision: Union[str, None] = 'cfcf3fd63cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaching_knowledge_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('methodology', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('text_chunk', sa.Text(), nullable=False),
    sa.Column('extracted_principles', sa.Text(), nullable=True),
    sa.Column('principle_type', sa.Text(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_methodology', 'coaching_knowledge_entry', ['methodology'], unique=False)
    op.create_index('ix_knowledge_principle_type', 'coaching_knowledge_entry', ['principle_type'], unique=False)
    op.create_table('coaching_recommendation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.Text(), nullable=False),
    sa.Column('recommendation_json', sa.Text(), nullable=False),
    sa.Column('knowledge_entry_ids', sa.Text(), nullable=True),
    sa.Column('diagnostic_signals_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('outcome_tracked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_athlete_id', 'coaching_recommendation', ['athlete_id'], unique=False)
    op.create_index('ix_recommendation_status', 'coaching_recommendation', ['status'], unique=False)
    op.create_index('ix_recommendation_type', 'coaching_recommendation', ['recommendation_type'], unique=False)
    op.create_table('recommendation_outcome',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tracked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('outcome_type', sa.Text(), nullable=False),
    sa.Column('outcome_data_json', sa.Text(), nullable=False),
    sa.Column('efficiency_trend', sa.Float(), nullable=True),
    sa.Column('pb_probability', sa.Float(), nullable=True),
    sa.Column('other_metrics_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['coaching_recommendation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outcome_recommendation_id', 'recommendation_outcome', ['recommendation_id'], unique=False)
    op.create_index('ix_outcome_type', 'recommendation_outcome', ['outcome_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outcome_type', table_name='recommendation_outcome')
    op.drop_index('ix_outcome_recommendation_id', table_name='recommendation_outcome')
    op.drop_table('recommendation_outcome')
    op.drop_index('ix_recommendation_type', table_name='coaching_recommendation')
    op.drop_index('ix_recommendation_status', table_name='coaching_recommendation')
    op.drop_index('ix_recommendation_athlete_id', table_name='coaching_recommendation')
    op.drop_table('coaching_recommendation')
    op.drop_index('ix_knowledge_principle_type', table_name='coaching_knowledge_entry')
    op.drop_index('ix_knowledge_methodology', table_name='coaching_knowledge_entry')
    op.drop_table('coaching_knowledge_entry')
    # ### end Alembic commands ###




