"""add strava fields

Revision ID: 30e143fe0da9
Revises: 001
Create Date: 2026-01-01 23:24:34.911562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e143fe0da9'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete', sa.Column('strava_athlete_id', sa.Integer(), nullable=True))
    op.add_column('athlete', sa.Column('strava_access_token', sa.Text(), nullable=True))
    op.add_column('athlete', sa.Column('strava_refresh_token', sa.Text(), nullable=True))
    op.add_column('athlete', sa.Column('last_strava_sync', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_athlete_email', table_name='athlete')
    op.create_unique_constraint(None, 'athlete', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'athlete', type_='unique')
    op.create_index('ix_athlete_email', 'athlete', ['email'], unique=False)
    op.drop_column('athlete', 'last_strava_sync')
    op.drop_column('athlete', 'strava_refresh_token')
    op.drop_column('athlete', 'strava_access_token')
    op.drop_column('athlete', 'strava_athlete_id')
    # ### end Alembic commands ###


