"""add_derived_signals_to_athlete

Revision ID: 3a855d49b512
Revises: d4f5e6a7b8c9
Create Date: 2026-01-04 14:48:24.788155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a855d49b512'
down_revision: Union[str, None] = 'd4f5e6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'is_race_candidate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('activity', 'race_confidence',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('activity', 'user_verified_race',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_activity_external_activity_id'), 'activity', ['external_activity_id'], unique=False)
    op.create_index(op.f('ix_activity_provider'), 'activity', ['provider'], unique=False)
    op.create_unique_constraint('uq_activity_split_number', 'activity_split', ['activity_id', 'split_number'])
    op.add_column('athlete', sa.Column('durability_index', sa.Float(), nullable=True))
    op.add_column('athlete', sa.Column('recovery_half_life_hours', sa.Float(), nullable=True))
    op.add_column('athlete', sa.Column('consistency_index', sa.Float(), nullable=True))
    op.add_column('athlete', sa.Column('last_metrics_calculation', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athlete', 'last_metrics_calculation')
    op.drop_column('athlete', 'consistency_index')
    op.drop_column('athlete', 'recovery_half_life_hours')
    op.drop_column('athlete', 'durability_index')
    op.drop_constraint('uq_activity_split_number', 'activity_split', type_='unique')
    op.drop_index(op.f('ix_activity_provider'), table_name='activity')
    op.drop_index(op.f('ix_activity_external_activity_id'), table_name='activity')
    op.alter_column('activity', 'user_verified_race',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('activity', 'race_confidence',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('activity', 'is_race_candidate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###



