"""add_name_to_activity

Revision ID: 57eb2e1473e1
Revises: b191d11a99b4
Create Date: 2026-01-09 08:40:59.303281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57eb2e1473e1'
down_revision: Union[str, None] = 'b191d11a99b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'name')
    # ### end Alembic commands ###




