"""add_personal_best_table

Revision ID: 860d504e676f
Revises: 3a855d49b512
Create Date: 2026-01-04 15:09:13.005825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860d504e676f'
down_revision: Union[str, None] = '3a855d49b512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_best',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('distance_category', sa.Text(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=False),
    sa.Column('pace_per_mile', sa.Float(), nullable=True),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_race', sa.Boolean(), nullable=True),
    sa.Column('age_at_achievement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'distance_category', name='uq_personal_best_athlete_distance')
    )
    op.create_index('ix_personal_best_athlete_id', 'personal_best', ['athlete_id'], unique=False)
    op.create_index('ix_personal_best_distance_category', 'personal_best', ['distance_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_personal_best_distance_category', table_name='personal_best')
    op.drop_index('ix_personal_best_athlete_id', table_name='personal_best')
    op.drop_table('personal_best')
    # ### end Alembic commands ###



