"""add_missing_athlete_columns

Revision ID: 9033f613c815
Revises: c10a0b1c2d3e
Create Date: 2026-01-31 09:06:56.058102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9033f613c815'
down_revision: Union[str, None] = 'c10a0b1c2d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_composition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(), nullable=True),
    sa.Column('body_fat_pct', sa.Numeric(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Numeric(), nullable=True),
    sa.Column('bmi', sa.Numeric(), nullable=True),
    sa.Column('measurements_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'date', name='uq_body_composition_athlete_date')
    )
    op.create_index('ix_body_composition_athlete_date', 'body_composition', ['athlete_id', 'date'], unique=False)
    op.create_index(op.f('ix_body_composition_athlete_id'), 'body_composition', ['athlete_id'], unique=False)
    op.create_table('insight_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.Text(), nullable=False),
    sa.Column('insight_id', sa.Text(), nullable=True),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insight_feedback_athlete_id', 'insight_feedback', ['athlete_id'], unique=False)
    op.create_index('ix_insight_feedback_created_at', 'insight_feedback', ['created_at'], unique=False)
    op.create_index('ix_insight_feedback_insight_type', 'insight_feedback', ['insight_type'], unique=False)
    op.create_table('intake_questionnaire',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_questionnaire_athlete_id'), 'intake_questionnaire', ['athlete_id'], unique=False)
    op.create_index('ix_intake_questionnaire_athlete_stage', 'intake_questionnaire', ['athlete_id', 'stage'], unique=False)
    op.create_table('training_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('time_block', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'day_of_week', 'time_block', name='uq_training_availability_athlete_day_block')
    )
    op.create_index('ix_training_availability_athlete_id', 'training_availability', ['athlete_id'], unique=False)
    op.create_index('ix_training_availability_day_block', 'training_availability', ['athlete_id', 'day_of_week', 'time_block'], unique=False)
    op.create_table('work_pattern',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('work_type', sa.Text(), nullable=True),
    sa.Column('hours_worked', sa.Numeric(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'date', name='uq_work_pattern_athlete_date')
    )
    op.create_index('ix_work_pattern_athlete_date', 'work_pattern', ['athlete_id', 'date'], unique=False)
    op.create_index(op.f('ix_work_pattern_athlete_id'), 'work_pattern', ['athlete_id'], unique=False)
    op.create_table('activity_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('perceived_effort', sa.Integer(), nullable=True),
    sa.Column('leg_feel', sa.Text(), nullable=True),
    sa.Column('mood_pre', sa.Text(), nullable=True),
    sa.Column('mood_post', sa.Text(), nullable=True),
    sa.Column('energy_pre', sa.Integer(), nullable=True),
    sa.Column('energy_post', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', name='uq_activity_feedback_activity')
    )
    op.create_index('ix_activity_feedback_activity_id', 'activity_feedback', ['activity_id'], unique=False)
    op.create_index('ix_activity_feedback_athlete_id', 'activity_feedback', ['athlete_id'], unique=False)
    op.create_index('ix_activity_feedback_submitted_at', 'activity_feedback', ['submitted_at'], unique=False)
    op.create_table('nutrition_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.Text(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('calories', sa.Numeric(), nullable=True),
    sa.Column('protein_g', sa.Numeric(), nullable=True),
    sa.Column('carbs_g', sa.Numeric(), nullable=True),
    sa.Column('fat_g', sa.Numeric(), nullable=True),
    sa.Column('fiber_g', sa.Numeric(), nullable=True),
    sa.Column('timing', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nutrition_athlete_date', 'nutrition_entry', ['athlete_id', 'date'], unique=False)
    op.create_index(op.f('ix_nutrition_entry_athlete_id'), 'nutrition_entry', ['athlete_id'], unique=False)
    op.add_column('activity_split', sa.Column('gap_seconds_per_mile', sa.Numeric(), nullable=True))
    op.add_column('athlete', sa.Column('password_hash', sa.Text(), nullable=True))
    op.add_column('athlete', sa.Column('role', sa.Text(), nullable=False, server_default='athlete'))
    op.add_column('athlete', sa.Column('height_cm', sa.Numeric(), nullable=True))
    op.add_column('athlete', sa.Column('onboarding_stage', sa.Text(), nullable=True))
    op.add_column('athlete', sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('athlete', sa.Column('max_hr', sa.Integer(), nullable=True))
    op.add_column('athlete', sa.Column('resting_hr', sa.Integer(), nullable=True))
    op.add_column('athlete', sa.Column('threshold_hr', sa.Integer(), nullable=True))
    op.add_column('athlete', sa.Column('runner_type', sa.Text(), nullable=True))
    op.add_column('athlete', sa.Column('current_streak_weeks', sa.Integer(), nullable=True))
    op.add_column('athlete', sa.Column('longest_streak_weeks', sa.Integer(), nullable=True))
    op.drop_index('ix_athlete_ingestion_state_deferred_until', table_name='athlete_ingestion_state')
    op.add_column('athlete_learning', sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('athlete_learning', sa.Column('invalidation_reason', sa.Text(), nullable=True))
    op.drop_index('ix_athlete_learning_active', table_name='athlete_learning')
    op.drop_index('ix_athlete_learning_subject', table_name='athlete_learning')
    op.create_index('ix_athlete_learning_athlete_type', 'athlete_learning', ['athlete_id', 'learning_type'], unique=False)
    op.drop_constraint('athlete_learning_superseded_by_fkey', 'athlete_learning', type_='foreignkey')
    op.drop_column('athlete_learning', 'superseded_by')
    op.drop_index('ix_race_anchor_athlete_id', table_name='athlete_race_result_anchor')
    op.drop_index('ix_race_anchor_distance_key', table_name='athlete_race_result_anchor')
    op.drop_constraint('uq_race_anchor_athlete', 'athlete_race_result_anchor', type_='unique')
    op.create_index(op.f('ix_athlete_race_result_anchor_athlete_id'), 'athlete_race_result_anchor', ['athlete_id'], unique=True)
    op.drop_index('ix_training_pace_profile_athlete_id', table_name='athlete_training_pace_profile')
    op.drop_index('ix_training_pace_profile_race_anchor_id', table_name='athlete_training_pace_profile')
    op.drop_constraint('uq_training_pace_profile_athlete', 'athlete_training_pace_profile', type_='unique')
    op.create_index(op.f('ix_athlete_training_pace_profile_athlete_id'), 'athlete_training_pace_profile', ['athlete_id'], unique=True)
    op.create_index(op.f('ix_athlete_training_pace_profile_race_anchor_id'), 'athlete_training_pace_profile', ['race_anchor_id'], unique=False)
    op.drop_constraint('coach_intent_snapshot_athlete_id_key', 'coach_intent_snapshot', type_='unique')
    op.drop_index('ix_coach_intent_snapshot_athlete_id', table_name='coach_intent_snapshot')
    op.create_index(op.f('ix_coach_intent_snapshot_athlete_id'), 'coach_intent_snapshot', ['athlete_id'], unique=True)
    op.drop_index('ix_invite_allowlist_is_active', table_name='invite_allowlist')
    op.drop_constraint('uq_invite_allowlist_email', 'invite_allowlist', type_='unique')
    op.drop_index('ix_invite_allowlist_email', table_name='invite_allowlist')
    op.create_index(op.f('ix_invite_allowlist_email'), 'invite_allowlist', ['email'], unique=True)
    op.drop_constraint('uq_subscriptions_athlete_id', 'subscriptions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_subscriptions_athlete_id', 'subscriptions', ['athlete_id'])
    op.drop_index(op.f('ix_invite_allowlist_email'), table_name='invite_allowlist')
    op.create_index('ix_invite_allowlist_email', 'invite_allowlist', ['email'], unique=False)
    op.create_unique_constraint('uq_invite_allowlist_email', 'invite_allowlist', ['email'])
    op.create_index('ix_invite_allowlist_is_active', 'invite_allowlist', ['is_active'], unique=False)
    op.drop_index(op.f('ix_coach_intent_snapshot_athlete_id'), table_name='coach_intent_snapshot')
    op.create_index('ix_coach_intent_snapshot_athlete_id', 'coach_intent_snapshot', ['athlete_id'], unique=False)
    op.create_unique_constraint('coach_intent_snapshot_athlete_id_key', 'coach_intent_snapshot', ['athlete_id'])
    op.drop_index(op.f('ix_athlete_training_pace_profile_race_anchor_id'), table_name='athlete_training_pace_profile')
    op.drop_index(op.f('ix_athlete_training_pace_profile_athlete_id'), table_name='athlete_training_pace_profile')
    op.create_unique_constraint('uq_training_pace_profile_athlete', 'athlete_training_pace_profile', ['athlete_id'])
    op.create_index('ix_training_pace_profile_race_anchor_id', 'athlete_training_pace_profile', ['race_anchor_id'], unique=False)
    op.create_index('ix_training_pace_profile_athlete_id', 'athlete_training_pace_profile', ['athlete_id'], unique=False)
    op.drop_index(op.f('ix_athlete_race_result_anchor_athlete_id'), table_name='athlete_race_result_anchor')
    op.create_unique_constraint('uq_race_anchor_athlete', 'athlete_race_result_anchor', ['athlete_id'])
    op.create_index('ix_race_anchor_distance_key', 'athlete_race_result_anchor', ['distance_key'], unique=False)
    op.create_index('ix_race_anchor_athlete_id', 'athlete_race_result_anchor', ['athlete_id'], unique=False)
    op.add_column('athlete_learning', sa.Column('superseded_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('athlete_learning_superseded_by_fkey', 'athlete_learning', 'athlete_learning', ['superseded_by'], ['id'])
    op.drop_index('ix_athlete_learning_athlete_type', table_name='athlete_learning')
    op.create_index('ix_athlete_learning_subject', 'athlete_learning', ['subject'], unique=False)
    op.create_index('ix_athlete_learning_active', 'athlete_learning', ['is_active'], unique=False)
    op.drop_column('athlete_learning', 'invalidation_reason')
    op.drop_column('athlete_learning', 'invalidated_at')
    op.create_index('ix_athlete_ingestion_state_deferred_until', 'athlete_ingestion_state', ['deferred_until'], unique=False)
    op.drop_column('athlete', 'longest_streak_weeks')
    op.drop_column('athlete', 'current_streak_weeks')
    op.drop_column('athlete', 'runner_type')
    op.drop_column('athlete', 'threshold_hr')
    op.drop_column('athlete', 'resting_hr')
    op.drop_column('athlete', 'max_hr')
    op.drop_column('athlete', 'onboarding_completed')
    op.drop_column('athlete', 'onboarding_stage')
    op.drop_column('athlete', 'height_cm')
    op.drop_column('athlete', 'role')
    op.drop_column('athlete', 'password_hash')
    op.drop_column('activity_split', 'gap_seconds_per_mile')
    op.drop_index(op.f('ix_nutrition_entry_athlete_id'), table_name='nutrition_entry')
    op.drop_index('ix_nutrition_athlete_date', table_name='nutrition_entry')
    op.drop_table('nutrition_entry')
    op.drop_index('ix_activity_feedback_submitted_at', table_name='activity_feedback')
    op.drop_index('ix_activity_feedback_athlete_id', table_name='activity_feedback')
    op.drop_index('ix_activity_feedback_activity_id', table_name='activity_feedback')
    op.drop_table('activity_feedback')
    op.drop_index(op.f('ix_work_pattern_athlete_id'), table_name='work_pattern')
    op.drop_index('ix_work_pattern_athlete_date', table_name='work_pattern')
    op.drop_table('work_pattern')
    op.drop_index('ix_training_availability_day_block', table_name='training_availability')
    op.drop_index('ix_training_availability_athlete_id', table_name='training_availability')
    op.drop_table('training_availability')
    op.drop_index('ix_intake_questionnaire_athlete_stage', table_name='intake_questionnaire')
    op.drop_index(op.f('ix_intake_questionnaire_athlete_id'), table_name='intake_questionnaire')
    op.drop_table('intake_questionnaire')
    op.drop_index('ix_insight_feedback_insight_type', table_name='insight_feedback')
    op.drop_index('ix_insight_feedback_created_at', table_name='insight_feedback')
    op.drop_index('ix_insight_feedback_athlete_id', table_name='insight_feedback')
    op.drop_table('insight_feedback')
    op.drop_index(op.f('ix_body_composition_athlete_id'), table_name='body_composition')
    op.drop_index('ix_body_composition_athlete_date', table_name='body_composition')
    op.drop_table('body_composition')
    # ### end Alembic commands ###




