"""add_preferred_units_to_athlete

Revision ID: a08aa0fceae2
Revises: b7eda0eabd7f
Create Date: 2026-01-09 07:02:00.598114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08aa0fceae2'
down_revision: Union[str, None] = 'b7eda0eabd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server default for existing rows
    op.add_column('athlete', sa.Column('preferred_units', sa.Text(), nullable=False, server_default='metric'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athlete', 'preferred_units')
    # ### end Alembic commands ###




