"""Add plan_adaptation_proposal table for adaptive re-plan.

Stores proposed plan adjustments generated by the adaptive replanner.
Each proposal captures trigger reason, proposed day-level changes,
original plan snapshot, and athlete response (accept/reject/expired).

Revision ID: adaptive_replan_001
Revises: adaptive_replan_000
Create Date: 2026-04-04
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB


revision = "adaptive_replan_001"
down_revision = "adaptive_replan_000"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "plan_adaptation_proposal",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("athlete_id", UUID(as_uuid=True), sa.ForeignKey("athlete.id"), nullable=False),
        sa.Column("plan_id", UUID(as_uuid=True), sa.ForeignKey("training_plan.id"), nullable=False),

        # What triggered the adaptation
        sa.Column("trigger_type", sa.Text(), nullable=False),
        sa.Column("trigger_detail", JSONB(), nullable=True),

        # Proposed changes (list of day-level diffs)
        sa.Column("proposed_changes", JSONB(), nullable=False),
        # Snapshot of original workouts being replaced
        sa.Column("original_snapshot", JSONB(), nullable=False),
        # Scope: which weeks are affected
        sa.Column("affected_week_start", sa.Integer(), nullable=False),
        sa.Column("affected_week_end", sa.Integer(), nullable=False),

        # Lifecycle
        sa.Column("status", sa.Text(), nullable=False, server_default="pending"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),

        # Guardrail tracking
        sa.Column("adaptation_number", sa.Integer(), nullable=False, server_default="1"),
    )

    op.create_index("ix_pap_athlete_status", "plan_adaptation_proposal", ["athlete_id", "status"])
    op.create_index("ix_pap_plan_id", "plan_adaptation_proposal", ["plan_id"])
    op.create_index("ix_pap_expires_at", "plan_adaptation_proposal", ["expires_at"])


def downgrade():
    op.drop_index("ix_pap_expires_at")
    op.drop_index("ix_pap_plan_id")
    op.drop_index("ix_pap_athlete_status")
    op.drop_table("plan_adaptation_proposal")
