"""add_workout_classification_to_activity

Revision ID: b191d11a99b4
Revises: a08aa0fceae2
Create Date: 2026-01-09 07:44:23.097057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b191d11a99b4'
down_revision: Union[str, None] = 'a08aa0fceae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('workout_type', sa.Text(), nullable=True))
    op.add_column('activity', sa.Column('workout_zone', sa.Text(), nullable=True))
    op.add_column('activity', sa.Column('workout_confidence', sa.Float(), nullable=True))
    op.add_column('activity', sa.Column('intensity_score', sa.Float(), nullable=True))
    op.add_column('activity', sa.Column('temperature_f', sa.Float(), nullable=True))
    op.add_column('activity', sa.Column('humidity_pct', sa.Float(), nullable=True))
    op.add_column('activity', sa.Column('weather_condition', sa.Text(), nullable=True))
    op.create_index(op.f('ix_activity_workout_type'), 'activity', ['workout_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_workout_type'), table_name='activity')
    op.drop_column('activity', 'weather_condition')
    op.drop_column('activity', 'humidity_pct')
    op.drop_column('activity', 'temperature_f')
    op.drop_column('activity', 'intensity_score')
    op.drop_column('activity', 'workout_confidence')
    op.drop_column('activity', 'workout_zone')
    op.drop_column('activity', 'workout_type')
    # ### end Alembic commands ###




