"""add_training_plan_and_planned_workout

Revision ID: b7eda0eabd7f
Revises: 728acc5f0965
Create Date: 2026-01-09 01:05:48.913203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7eda0eabd7f'
down_revision: Union[str, None] = '728acc5f0965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('goal_race_name', sa.Text(), nullable=True),
    sa.Column('goal_race_date', sa.Date(), nullable=False),
    sa.Column('goal_race_distance_m', sa.Integer(), nullable=False),
    sa.Column('goal_time_seconds', sa.Integer(), nullable=True),
    sa.Column('plan_start_date', sa.Date(), nullable=False),
    sa.Column('plan_end_date', sa.Date(), nullable=False),
    sa.Column('total_weeks', sa.Integer(), nullable=False),
    sa.Column('baseline_vdot', sa.Float(), nullable=True),
    sa.Column('baseline_weekly_volume_km', sa.Float(), nullable=True),
    sa.Column('plan_type', sa.Text(), nullable=False),
    sa.Column('generation_method', sa.Text(), nullable=False),
    sa.Column('methodology_blend', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_plan_athlete_id', 'training_plan', ['athlete_id'], unique=False)
    op.create_index('ix_training_plan_goal_date', 'training_plan', ['goal_race_date'], unique=False)
    op.create_index('ix_training_plan_status', 'training_plan', ['status'], unique=False)
    op.create_table('planned_workout',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('workout_type', sa.Text(), nullable=False),
    sa.Column('workout_subtype', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('phase_week', sa.Integer(), nullable=True),
    sa.Column('target_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('target_distance_km', sa.Float(), nullable=True),
    sa.Column('target_pace_per_km_seconds', sa.Integer(), nullable=True),
    sa.Column('target_pace_per_km_seconds_max', sa.Integer(), nullable=True),
    sa.Column('target_hr_min', sa.Integer(), nullable=True),
    sa.Column('target_hr_max', sa.Integer(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_activity_id', sa.UUID(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('coach_notes', sa.Text(), nullable=True),
    sa.Column('athlete_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['completed_activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'scheduled_date', name='uq_planned_workout_plan_date')
    )
    op.create_index('ix_planned_workout_athlete_id', 'planned_workout', ['athlete_id'], unique=False)
    op.create_index('ix_planned_workout_date', 'planned_workout', ['scheduled_date'], unique=False)
    op.create_index('ix_planned_workout_plan_date', 'planned_workout', ['plan_id', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_planned_workout_plan_id'), 'planned_workout', ['plan_id'], unique=False)
    op.drop_index('ix_activity_athlete_start_time', table_name='activity')
    op.drop_index('ix_activity_avg_hr', table_name='activity')
    op.drop_index('ix_activity_distance', table_name='activity')
    op.drop_index('ix_activity_is_race_candidate', table_name='activity')
    op.drop_index('ix_activity_sport', table_name='activity')
    op.drop_index('ix_activity_start_time', table_name='activity')
    op.drop_index('ix_activity_user_verified_race', table_name='activity')
    op.drop_index('ix_activity_split_activity_split_number', table_name='activity_split')
    op.alter_column('athlete', 'threshold_pace_per_km',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('athlete', 'vdot',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('athlete', 'runner_type_confidence',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('athlete', 'runner_type_last_calculated',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('athlete', 'last_streak_update',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_body_composition_athlete_id'), 'body_composition', ['athlete_id'], unique=False)
    op.add_column('daily_checkin', sa.Column('enjoyment_1_5', sa.Integer(), nullable=True))
    op.add_column('daily_checkin', sa.Column('confidence_1_5', sa.Integer(), nullable=True))
    op.add_column('daily_checkin', sa.Column('motivation_1_5', sa.Integer(), nullable=True))
    op.drop_index('ix_daily_checkin_athlete_date', table_name='daily_checkin')
    op.create_index(op.f('ix_intake_questionnaire_athlete_id'), 'intake_questionnaire', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_nutrition_entry_athlete_id'), 'nutrition_entry', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_work_pattern_athlete_id'), 'work_pattern', ['athlete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_pattern_athlete_id'), table_name='work_pattern')
    op.drop_index(op.f('ix_nutrition_entry_athlete_id'), table_name='nutrition_entry')
    op.drop_index(op.f('ix_intake_questionnaire_athlete_id'), table_name='intake_questionnaire')
    op.create_index('ix_daily_checkin_athlete_date', 'daily_checkin', ['athlete_id', 'date'], unique=False)
    op.drop_column('daily_checkin', 'motivation_1_5')
    op.drop_column('daily_checkin', 'confidence_1_5')
    op.drop_column('daily_checkin', 'enjoyment_1_5')
    op.drop_index(op.f('ix_body_composition_athlete_id'), table_name='body_composition')
    op.alter_column('athlete', 'last_streak_update',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('athlete', 'runner_type_last_calculated',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('athlete', 'runner_type_confidence',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('athlete', 'vdot',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('athlete', 'threshold_pace_per_km',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.create_index('ix_activity_split_activity_split_number', 'activity_split', ['activity_id', 'split_number'], unique=False)
    op.create_index('ix_activity_user_verified_race', 'activity', ['user_verified_race'], unique=False)
    op.create_index('ix_activity_start_time', 'activity', ['start_time'], unique=False)
    op.create_index('ix_activity_sport', 'activity', ['sport'], unique=False)
    op.create_index('ix_activity_is_race_candidate', 'activity', ['is_race_candidate'], unique=False)
    op.create_index('ix_activity_distance', 'activity', ['distance_m'], unique=False)
    op.create_index('ix_activity_avg_hr', 'activity', ['avg_hr'], unique=False)
    op.create_index('ix_activity_athlete_start_time', 'activity', ['athlete_id', 'start_time'], unique=False)
    op.drop_index(op.f('ix_planned_workout_plan_id'), table_name='planned_workout')
    op.drop_index('ix_planned_workout_plan_date', table_name='planned_workout')
    op.drop_index('ix_planned_workout_date', table_name='planned_workout')
    op.drop_index('ix_planned_workout_athlete_id', table_name='planned_workout')
    op.drop_table('planned_workout')
    op.drop_index('ix_training_plan_status', table_name='training_plan')
    op.drop_index('ix_training_plan_goal_date', table_name='training_plan')
    op.drop_index('ix_training_plan_athlete_id', table_name='training_plan')
    op.drop_table('training_plan')
    # ### end Alembic commands ###




