"""add_performance_metrics

Revision ID: c820b73b7010
Revises: 30e143fe0da9
Create Date: 2026-01-02 07:35:33.112020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c820b73b7010'
down_revision: Union[str, None] = '30e143fe0da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('max_hr', sa.Integer(), nullable=True))
    op.add_column('activity', sa.Column('total_elevation_gain', sa.Numeric(), nullable=True))
    op.add_column('activity', sa.Column('average_speed', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'average_speed')
    op.drop_column('activity', 'total_elevation_gain')
    op.drop_column('activity', 'max_hr')
    # ### end Alembic commands ###



