"""add_best_effort_table

Revision ID: df6a2e9fd0ec
Revises: add_plan_mod_log
Create Date: 2026-01-12 18:53:33.897216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df6a2e9fd0ec'
down_revision: Union[str, None] = 'add_plan_mod_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phase_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('applicable_distances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_weeks', sa.Integer(), nullable=False),
    sa.Column('min_weeks', sa.Integer(), nullable=False),
    sa.Column('max_weeks', sa.Integer(), nullable=False),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('quality_sessions_per_week', sa.Integer(), nullable=False),
    sa.Column('allowed_workout_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phase_definition_key'), 'phase_definition', ['key'], unique=True)
    op.create_table('plan_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('distance', sa.Text(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('volume_tier', sa.Text(), nullable=False),
    sa.Column('starting_volume_miles', sa.Float(), nullable=False),
    sa.Column('peak_volume_miles', sa.Float(), nullable=False),
    sa.Column('long_run_start_miles', sa.Float(), nullable=False),
    sa.Column('long_run_peak_miles', sa.Float(), nullable=False),
    sa.Column('phases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weekly_structures', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_template_distance'), 'plan_template', ['distance'], unique=False)
    op.create_index('ix_plan_template_distance_duration', 'plan_template', ['distance', 'duration_weeks'], unique=False)
    op.create_index(op.f('ix_plan_template_key'), 'plan_template', ['key'], unique=True)
    op.create_index(op.f('ix_plan_template_volume_tier'), 'plan_template', ['volume_tier'], unique=False)
    op.create_table('scaling_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('rule_logic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scaling_rule_category'), 'scaling_rule', ['category'], unique=False)
    op.create_index(op.f('ix_scaling_rule_key'), 'scaling_rule', ['key'], unique=True)
    op.create_table('workout_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applicable_distances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applicable_phases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('structure_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scaling_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('option_b_key', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('when_to_use', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_definition_category'), 'workout_definition', ['category'], unique=False)
    op.create_index(op.f('ix_workout_definition_key'), 'workout_definition', ['key'], unique=True)
    op.create_table('athlete_goal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('goal_distance', sa.Text(), nullable=False),
    sa.Column('goal_race_date', sa.Date(), nullable=False),
    sa.Column('current_weekly_miles', sa.Float(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('recent_race_distance', sa.Text(), nullable=True),
    sa.Column('recent_race_time_seconds', sa.Integer(), nullable=True),
    sa.Column('goal_time_seconds', sa.Integer(), nullable=True),
    sa.Column('current_long_run_miles', sa.Float(), nullable=True),
    sa.Column('race_profile', sa.Text(), nullable=True),
    sa.Column('race_season', sa.Text(), nullable=True),
    sa.Column('injury_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('training_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_athlete_goal_athlete_id', 'athlete_goal', ['athlete_id'], unique=False)
    op.create_index('ix_athlete_goal_race_date', 'athlete_goal', ['goal_race_date'], unique=False)
    op.create_table('purchase',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('product_key', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payment_provider', sa.Text(), nullable=True),
    sa.Column('external_payment_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_athlete_id'), 'purchase', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_purchase_product_key'), 'purchase', ['product_key'], unique=False)
    op.create_table('best_effort',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('distance_category', sa.Text(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('elapsed_time', sa.Integer(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strava_effort_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'strava_effort_id', name='uq_best_effort_activity_strava')
    )
    op.create_index('ix_best_effort_activity_id', 'best_effort', ['activity_id'], unique=False)
    op.create_index('ix_best_effort_athlete_id', 'best_effort', ['athlete_id'], unique=False)
    op.create_index('ix_best_effort_distance_category', 'best_effort', ['distance_category'], unique=False)
    op.alter_column('feature_flag', 'rollout_percentage',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('feature_flag', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('feature_flag', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('feature_flag_key_key', 'feature_flag', type_='unique')
    op.drop_index('ix_feature_flag_key', table_name='feature_flag')
    op.create_index(op.f('ix_feature_flag_key'), 'feature_flag', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_flag_key'), table_name='feature_flag')
    op.create_index('ix_feature_flag_key', 'feature_flag', ['key'], unique=False)
    op.create_unique_constraint('feature_flag_key_key', 'feature_flag', ['key'])
    op.alter_column('feature_flag', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feature_flag', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feature_flag', 'rollout_percentage',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.drop_index('ix_best_effort_distance_category', table_name='best_effort')
    op.drop_index('ix_best_effort_athlete_id', table_name='best_effort')
    op.drop_index('ix_best_effort_activity_id', table_name='best_effort')
    op.drop_table('best_effort')
    op.drop_index(op.f('ix_purchase_product_key'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_athlete_id'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index('ix_athlete_goal_race_date', table_name='athlete_goal')
    op.drop_index('ix_athlete_goal_athlete_id', table_name='athlete_goal')
    op.drop_table('athlete_goal')
    op.drop_index(op.f('ix_workout_definition_key'), table_name='workout_definition')
    op.drop_index(op.f('ix_workout_definition_category'), table_name='workout_definition')
    op.drop_table('workout_definition')
    op.drop_index(op.f('ix_scaling_rule_key'), table_name='scaling_rule')
    op.drop_index(op.f('ix_scaling_rule_category'), table_name='scaling_rule')
    op.drop_table('scaling_rule')
    op.drop_index(op.f('ix_plan_template_volume_tier'), table_name='plan_template')
    op.drop_index(op.f('ix_plan_template_key'), table_name='plan_template')
    op.drop_index('ix_plan_template_distance_duration', table_name='plan_template')
    op.drop_index(op.f('ix_plan_template_distance'), table_name='plan_template')
    op.drop_table('plan_template')
    op.drop_index(op.f('ix_phase_definition_key'), table_name='phase_definition')
    op.drop_table('phase_definition')
    # ### end Alembic commands ###




